-- AlterTable
ALTER TABLE `clientes` ADD COLUMN `ativo` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `telefone` VARCHAR(15) NULL;

-- AlterTable
ALTER TABLE `propostas` ADD COLUMN `status` ENUM('PENDENTE', 'APROVADA', 'REJEITADA', 'CANCELADA') NOT NULL DEFAULT 'PENDENTE';
